### PR TITLE
Convert MedallionRandom to target .net standard 1.6 and .net Framewor…

### PR DESCRIPTION
**Pull request by pitming**
…k 4.5.2

Hi

I need your shuffle in a .net core project. So I just modified the project so It could target both framework.

Hope you'll make a new nuget package out of it.

Thx,

### CODE REVIEW

**Comment by madelson** [comment]
Hi @pitming thanks for your interest in the project. Supporting .NET Standard definitely makes sense for this library.

I tried building your branch locally but I can't load the project is VS2015 Community Edition. I get this error:

> the default xml namespace of the project must be the msbuild xml namespace

Any ideas? You are using a .NET Core project file format I'm not familiar with (I've only used project.json thus far). Maybe there's something I need to install or update to support that?

I'll also note that in the meantime if you are waiting for a new package version you can use the [Inline version of the package](https://www.nuget.org/packages/MedallionRandom.Inline/). That should be .NET Core compatible already since it simply drops a C# file into your project.

**Comment by pitming** [comment]
Hi csproj .NET Standard are only compatible with VS2017.

And for the project, there's no huge as I made a project reference to your clones library.

**Comment by madelson** [comment]
Thanks I'm going to give VS2017 a try. I'd been meaning to install it anyway.

**Comment by madelson** [comment]
Ok finally got this working (had to update the InlineNuGetPackage generator project to support the new csproj format)! The new 1.1.0 version of the package is published and supports .NET Standard 1.3. Give it a try and let me know if you have any issues.

**Pull request merged**
